package com.mx.mestudillo.vista;

import static com.mx.mestudillo.vista.LoginForm.conexion;
import static com.mx.mestudillo.vista.LoginForm.mensajes;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marco Estudillo
 */
public class BandejaForm extends javax.swing.JFrame {

    /**
     * Definición del modelo que se cargará a la tabla mensajes del formulario
     */
    private final DefaultTableModel modelo;
    private int noRegistro;

    /**
     * Se inicializan los componentes del formulario
     */
    public BandejaForm() {
        initComponents();

        // Se bloquea la edición de campos de la tabla usuarios, del formulario
        this.modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        // Se inicializan los campos del modelo que serán incluidos a la tabla
        this.modelo.addColumn("Remitente");
        this.modelo.addColumn("Asunto");
        tblMensajes.setModel(this.modelo);

        // Se obtienen los datos correspondientes de la bandeja de entrada
        getDatos();
        tblMensajes.setRowSelectionInterval(0, 0);
        getMensaje();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTotal = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMensajes = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblDevOps = new javax.swing.JTextField();
        lblFecha = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        editCuerpo = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bandeja de Entrada - DevOps");
        setPreferredSize(new java.awt.Dimension(780, 555));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(780, 530));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 230, 0));
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mx/mestudillo/imagen/mercado.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 300, 340));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 530));

        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 440, 10));

        lblTotal.setEditable(false);
        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblTotal.setText("Total");
        lblTotal.setFocusable(false);
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 200, 21));

        jPanel3.setBackground(new java.awt.Color(39, 52, 129));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mensajes Totales");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 190, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 200, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("Bandeja de Entrada - DevOps");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        jPanel4.setBackground(new java.awt.Color(39, 52, 129));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Mensajes");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 3, 410, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 420, 20));

        tblMensajes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblMensajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Remitente", "Asunto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMensajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMensajesMouseClicked(evt);
            }
        });
        tblMensajes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblMensajesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblMensajes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 420, 150));

        jPanel5.setBackground(new java.awt.Color(39, 52, 129));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 480, 30));

        jPanel6.setBackground(new java.awt.Color(39, 52, 129));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Mensajes con DevOps");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 190, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 200, 20));

        lblDevOps.setEditable(false);
        lblDevOps.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDevOps.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblDevOps.setText("DevOps");
        lblDevOps.setFocusable(false);
        jPanel1.add(lblDevOps, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 200, 21));

        lblFecha.setEditable(false);
        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lblFecha.setText("Fecha");
        lblFecha.setFocusable(false);
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 303, 210, 21));

        jPanel8.setBackground(new java.awt.Color(39, 52, 129));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cuerpo");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 190, -1));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 200, 20));

        editCuerpo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        editCuerpo.setForeground(new java.awt.Color(0, 51, 102));
        editCuerpo.setDisabledTextColor(new java.awt.Color(0, 51, 102));
        editCuerpo.setEnabled(false);
        jScrollPane2.setViewportView(editCuerpo);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 420, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que se encarga de cargar los datos del mensaje seleccionado con
     * las flechas del teclado
     */
    private void tblMensajesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblMensajesKeyReleased
        getMensaje();
    }//GEN-LAST:event_tblMensajesKeyReleased

    /**
     * Método que se encarga de cargar los datos del mensaje seleccionado con el
     * click del mouse
     */
    private void tblMensajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMensajesMouseClicked
        getMensaje();
    }//GEN-LAST:event_tblMensajesMouseClicked

    /**
     * Método que se encarga de cargar los datos de la bandeja de entrada
     */
    private void getDatos() {
        lblTotal.setText(String.valueOf(conexion.getTotal()));
        lblDevOps.setText(String.valueOf(conexion.getDevops()));

        for (int i = 0; i < mensajes.size(); i++) {
            this.modelo.addRow(new Object[]{mensajes.get(i).getRemitente(), mensajes.get(i).getAsunto()});
        }
    }

    /**
     * Método que se encarga de cargar los datos del mensaje seleccionado
     */
    private void getMensaje() {
        this.noRegistro = tblMensajes.getSelectedRow();
        lblFecha.setText(mensajes.get(this.noRegistro).getFecha());
        editCuerpo.setText(mensajes.get(this.noRegistro).getCuerpo());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BandejaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BandejaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BandejaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BandejaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BandejaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane editCuerpo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lblDevOps;
    private javax.swing.JTextField lblFecha;
    private javax.swing.JTextField lblTotal;
    private javax.swing.JTable tblMensajes;
    // End of variables declaration//GEN-END:variables
}
